version: "3"
services:
  tlw-laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tlw-laravel
    working_dir: /app
    volumes:
      - ./src:/app

  tlw-web:
    image: nginx
    container_name: tlw-web
    depends_on:
      - tlw-laravel
    environment:
      - NGINX_SERVER_NAME=_
      - NGINX_PORT=80
      - NGINX_SECURE_PORT=443
      - LARAVEL_HOST=tlw-laravel
      - LARAVEL_PORT=9000
      - NGINX_MAX_BODY=100M
      - NGINX_SSL_CERT=/certs/certificate.pem
      - NGINX_SSL_KEY=/certs/privatekey.pem
      - NGINX_SSL_DH=/certs/dh.pem
    command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/conf.d/vhost.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/app
      - ./certs/self-signed/certificate.pem:/certs/certificate.pem
      - ./certs/self-signed/privatekey.pem:/certs/privatekey.pem
      - ./certs/self-signed/dh.pem:/certs/dh.pem
      - ./configs/vhost.template:/etc/nginx/conf.d/vhost.template

  tlw-database:
    image: mariadb:10.2
    container_name: tlw-database
    environment:
      MYSQL_DATABASE: tlw
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mariadbdata:/var/lib/mysql

volumes:
  mariadbdata:
